name: Kong Lab Smoke Tests
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  install:
    name: Install Standalone Kong
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:slim-v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run install scripts
        run: run-all.sh
        env:
          KONG_LICENSE: ${{ secrets.KONG_LICENSE }}
