name: Kong Lab Smoke Tests
on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  install:
    name: Install Standalone Kong
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: docker://github/super-linter:slim-v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install deck
        run: curl -sL https://github.com/kong/deck/releases/download/v1.2.0/deck_1.2.0_linux_amd64.tar.gz -o deck.tar.gz && tar -xf deck.tar.gz -C /tmp && sudo cp /tmp/deck /usr/local/bin/
      - name: Run install scripts
        run: ./run-all.sh
        env:
          KONG_LICENSE: ${{ secrets.KONG_LICENSE }}
